// Constants for the deal checklist (ChecklistTab) — extracted from Pipeline.jsx
// so the tab component can live in its own file without dragging 200 lines of
// templates with it. Pure data, no React imports.

export const DEFAULT_STEPS_RESIDENTIAL = [
  'Title Search Ordered',
  'Earnest Money Deposited',
  'Home Inspection Scheduled',
  'Inspection Report Reviewed',
  'Appraisal Ordered',
  'Appraisal Report Received',
  'Financing Conditionally Approved',
  'Financing Fully Approved',
  'Final Walkthrough Scheduled',
  'Closing Disclosure Reviewed',
  'Closing Documents Signed',
  'Keys & Possession Transferred',
]

export const DEFAULT_STEPS_COMMERCIAL = [
  'Title Search Ordered',
  'Earnest Money Deposited',
  'Environmental Due Diligence (Phase I)',
  'Property Inspection Ordered',
  'Inspection Report Reviewed',
  'Survey Ordered',
  'Survey Received & Approved',
  'Zoning & Entitlements Verified',
  'Financing Commitment Received',
  'Lease Review (if applicable)',
  'Closing Disclosure Reviewed',
  'Closing Documents Signed',
  'Keys & Possession Transferred',
]

// Per-state, per-transaction-type document checklists (BoldTrail-style)
export const STATE_DOC_TEMPLATES = {
  'SD-seller': [
    { title: 'Submit Listing into MLS',                                                             doc_action: 'manual' },
    { title: 'All SD Agency & Listing Paperwork',                                                   doc_action: 'manual' },
    { title: 'Install Yard Sign',                                                                   doc_action: 'manual' },
    { title: 'Lockbox Authorization/Put on Property',                                               doc_action: 'manual' },
    { title: 'MLS Change Form',                                                                     doc_action: 'manual' },
    { title: 'Addendum to SPD',                                                                     doc_action: 'manual' },
    { title: "Seller's Property Disclosure",                                                        doc_action: 'manual' },
    { title: 'Lead-Based Paint/Radon Pamphlets Given',                                              doc_action: 'manual' },
    { title: 'Completed Purchase Agreement',                                                        doc_action: 'forms'  },
    { title: 'Earnest Money Deposit Receipt',                                                       doc_action: 'upload' },
    { title: "HOA Info/Disclosures sent to Buyer's Agent",                                          doc_action: 'manual' },
    { title: 'Termite Inspection Scheduled',                                                        doc_action: 'manual' },
    { title: 'Appraisal Scheduled',                                                                 doc_action: 'manual' },
    { title: 'Abstract dropped off at closing/abstract company',                                    doc_action: 'manual' },
    { title: 'Escrow Sheet',                                                                        doc_action: 'forms'  },
    { title: 'Closing Disclosure/Settlement Statement — Admin Only',                                doc_action: 'upload', admin_only: true },
    { title: 'Commission — Proof of Payment — Admin Only',                                          doc_action: 'upload', admin_only: true },
    { title: 'Retrieve Yard Sign',                                                                  doc_action: 'manual' },
    { title: 'Retrieve and Unassign Lockbox',                                                       doc_action: 'manual' },
    { title: 'Update Listing Site',                                                                 doc_action: 'manual' },
    { title: 'Inspection Addendums Submitted if any',                                               doc_action: 'upload', if_applicable: true },
    { title: 'Order Home Warranty if applicable',                                                   doc_action: 'forms',  if_applicable: true },
    { title: 'Addendums to Contract if applicable',                                                 doc_action: 'forms',  if_applicable: true },
    { title: 'MLS Listing Change Form if applicable',                                               doc_action: 'forms',  if_applicable: true },
  ],
  'SD-commercial': [
    { title: 'All SD Agency/Listing Paperwork',                                                     doc_action: 'manual' },
    { title: "Seller's Property & Lead Based Paint Disclosure",                                     doc_action: 'forms'  },
    { title: 'Lead-Based Paint/Radon Pamphlets Given',                                              doc_action: 'manual' },
    { title: 'Put onto listing site if applicable',                                                 doc_action: 'manual', if_applicable: true },
    { title: 'Install Sign if applicable',                                                          doc_action: 'manual', if_applicable: true },
    { title: 'Lockbox Authorization/Put on Property',                                               doc_action: 'manual' },
    { title: 'Completed Purchase Agreement',                                                        doc_action: 'forms'  },
    { title: 'Earnest Money Deposit Receipt',                                                       doc_action: 'upload' },
    { title: 'Escrow Sheet',                                                                        doc_action: 'forms'  },
    { title: 'Inspection Addendums Submitted if any',                                               doc_action: 'upload', if_applicable: true },
    { title: 'Closing Disclosure/Settlement Statement — Admin Only',                                doc_action: 'upload', admin_only: true },
    { title: 'Commission — Proof of Payment — Admin Only',                                          doc_action: 'upload', admin_only: true },
    { title: 'Retrieve and Unassign Lockbox',                                                       doc_action: 'manual' },
    { title: 'Remove Sign if applicable',                                                           doc_action: 'manual', if_applicable: true },
    { title: 'Update listing site if applicable',                                                   doc_action: 'manual', if_applicable: true },
    { title: 'Leases/expenses/rent/deposit prorations submitted to closing company if applicable',  doc_action: 'manual', if_applicable: true },
    { title: 'Any Addendums to Contract if applicable',                                             doc_action: 'manual', if_applicable: true },
  ],
  'SD-buyer': [
    { title: 'Buyer Representation Agreement',             doc_action: 'manual' },
    { title: 'Agency Disclosure',                          doc_action: 'manual' },
    { title: 'Purchase Agreement',                         doc_action: 'forms'  },
    { title: 'Lead-Based Paint Disclosure',                doc_action: 'manual', if_applicable: true },
    { title: 'Earnest Money Deposit Receipt',              doc_action: 'upload' },
    { title: 'Pre-Approval Letter',                        doc_action: 'upload' },
    { title: 'Home Inspection Report',                     doc_action: 'upload' },
    { title: 'Inspection Addendum / Response',             doc_action: 'forms',  if_applicable: true },
    { title: 'Financing Commitment Letter',                doc_action: 'upload' },
    { title: 'Appraisal Report',                           doc_action: 'upload', if_applicable: true },
    { title: 'Final Walkthrough Completed',                doc_action: 'manual' },
    { title: 'Closing Disclosure Reviewed',                doc_action: 'manual' },
    { title: 'Commission — Proof of Payment — Admin Only', doc_action: 'upload', admin_only: true },
    { title: 'Addendums to Contract if applicable',        doc_action: 'forms',  if_applicable: true },
  ],
  'IA-seller': [
    { title: 'All Iowa Agency & Listing Paperwork',                                                 doc_action: 'manual' },
    { title: 'Seller & Lead Based Paint Disclosure',                                                doc_action: 'forms'  },
    { title: 'Iowa Radon & Lead-Based Paint Pamphlets Given',                                       doc_action: 'manual' },
    { title: 'Submit Listing into MLS',                                                             doc_action: 'manual' },
    { title: 'Install yard sign if applicable',                                                     doc_action: 'manual', if_applicable: true },
    { title: 'Lockbox Authorization/Put on Property',                                               doc_action: 'manual' },
    { title: 'Termite Inspection Scheduled',                                                        doc_action: 'manual' },
    { title: 'Appraisal Scheduled',                                                                 doc_action: 'manual' },
    { title: 'Earnest Money Deposit Receipt',                                                       doc_action: 'upload' },
    { title: 'Abstract Dropped off at Closing Company/Abstract Company',                            doc_action: 'manual' },
    { title: 'Escrow Sheet',                                                                        doc_action: 'forms'  },
    { title: 'Closing Disclosure/Settlement Statement — Admin Only',                                doc_action: 'upload', admin_only: true },
    { title: 'Commission — Proof of Payment — Admin Only',                                          doc_action: 'upload', admin_only: true },
    { title: 'Update MLS',                                                                          doc_action: 'manual' },
    { title: 'Retrieve yard sign if applicable',                                                    doc_action: 'manual', if_applicable: true },
    { title: 'Retrieve lockbox & unassign property',                                                doc_action: 'manual' },
    { title: 'MLS Listing Change Form if applicable',                                               doc_action: 'forms',  if_applicable: true },
    { title: 'Any Addendums to Contract if applicable',                                             doc_action: 'upload', if_applicable: true },
    { title: 'Order Home Warranty if applicable',                                                   doc_action: 'forms',  if_applicable: true },
    { title: 'Inspection Addendums Submitted if any',                                               doc_action: 'upload', if_applicable: true },
  ],
  'IA-commercial': [
    { title: 'All IA Agency/Listing Paperwork',                                                     doc_action: 'manual' },
    { title: 'Put onto Listing site if applicable',                                                 doc_action: 'manual', if_applicable: true },
    { title: 'Install sign if applicable',                                                          doc_action: 'manual', if_applicable: true },
    { title: 'Lockbox Authorization/Put on property',                                               doc_action: 'manual' },
    { title: 'Purchase Agreement',                                                                  doc_action: 'forms'  },
    { title: 'Inspection Scheduled',                                                                doc_action: 'manual' },
    { title: 'Leases/expenses/rent/deposit prorations submitted to closing company if applicable',  doc_action: 'manual', if_applicable: true },
    { title: 'Escrow Sheet',                                                                        doc_action: 'forms'  },
    { title: 'Earnest Money Deposit Receipt',                                                       doc_action: 'upload' },
    { title: 'Closing Disclosure/Settlement Statement — Admin Only',                                doc_action: 'upload', admin_only: true },
    { title: 'Commission — Proof of Payment — Admin Only',                                          doc_action: 'upload', admin_only: true },
    { title: 'Update Listing site if applicable',                                                   doc_action: 'manual', if_applicable: true },
    { title: 'Retrieve lockbox/unassign from property',                                             doc_action: 'manual' },
    { title: 'Retrieve Sign if applicable',                                                         doc_action: 'manual', if_applicable: true },
    { title: 'Any Addendums to Contract if applicable',                                             doc_action: 'upload', if_applicable: true },
    { title: 'MLS Listing Change Form if applicable',                                               doc_action: 'forms',  if_applicable: true },
  ],
  'IA-buyer': [
    { title: 'Buyer Agency Agreement',                     doc_action: 'manual' },
    { title: 'Agency Disclosure',                          doc_action: 'manual' },
    { title: 'Purchase Agreement',                         doc_action: 'forms'  },
    { title: 'Earnest Money Deposit Receipt',              doc_action: 'upload' },
    { title: 'Pre-Approval Letter',                        doc_action: 'upload' },
    { title: 'Home Inspection Report',                     doc_action: 'upload' },
    { title: 'Inspection Addendum / Response',             doc_action: 'forms',  if_applicable: true },
    { title: 'Financing Commitment Letter',                doc_action: 'upload' },
    { title: 'Appraisal Report',                           doc_action: 'upload', if_applicable: true },
    { title: 'Final Walkthrough Completed',                doc_action: 'manual' },
    { title: 'Closing Disclosure Reviewed',                doc_action: 'manual' },
    { title: 'Commission — Proof of Payment — Admin Only', doc_action: 'upload', admin_only: true },
    { title: 'Addendums to Contract if applicable',        doc_action: 'forms',  if_applicable: true },
  ],
  'NE-seller': [
    { title: 'All NE Agency & Listing Paperwork',          doc_action: 'manual' },
    { title: 'NE Seller Property Condition Disclosure',    doc_action: 'manual' },
    { title: 'MLS Change Form',                            doc_action: 'manual' },
    { title: 'Lead-Based Paint Disclosure',                doc_action: 'manual', if_applicable: true },
    { title: 'Completed Purchase Agreement',               doc_action: 'forms'  },
    { title: 'Earnest Money Deposit Receipt',              doc_action: 'upload' },
    { title: 'Title Insurance Ordered',                    doc_action: 'manual' },
    { title: 'Escrow / Settlement Sheet',                  doc_action: 'forms'  },
    { title: 'Closing Disclosure/Settlement Statement — Admin Only', doc_action: 'upload', admin_only: true },
    { title: 'Commission — Proof of Payment — Admin Only', doc_action: 'upload', admin_only: true },
    { title: 'Inspection Addendums Submitted if any',      doc_action: 'upload', if_applicable: true },
    { title: 'Home Warranty Order if applicable',          doc_action: 'forms',  if_applicable: true },
    { title: 'Addendums to Contract if applicable',        doc_action: 'forms',  if_applicable: true },
    { title: 'MLS Listing Change Form if applicable',      doc_action: 'forms',  if_applicable: true },
  ],
  'NE-buyer': [
    { title: 'Buyer Representation Agreement',             doc_action: 'manual' },
    { title: 'Agency Disclosure',                          doc_action: 'manual' },
    { title: 'Purchase Agreement',                         doc_action: 'forms'  },
    { title: 'Lead-Based Paint Disclosure',                doc_action: 'manual', if_applicable: true },
    { title: 'Earnest Money Deposit Receipt',              doc_action: 'upload' },
    { title: 'Pre-Approval Letter',                        doc_action: 'upload' },
    { title: 'Home Inspection Report',                     doc_action: 'upload' },
    { title: 'Inspection Addendum / Response',             doc_action: 'forms',  if_applicable: true },
    { title: 'Financing Commitment Letter',                doc_action: 'upload' },
    { title: 'Title Commitment Received',                  doc_action: 'manual' },
    { title: 'Appraisal Report',                           doc_action: 'upload', if_applicable: true },
    { title: 'Final Walkthrough Completed',                doc_action: 'manual' },
    { title: 'Closing Disclosure Reviewed',                doc_action: 'manual' },
    { title: 'Commission — Proof of Payment — Admin Only', doc_action: 'upload', admin_only: true },
    { title: 'Addendums to Contract if applicable',        doc_action: 'forms',  if_applicable: true },
  ],
}

export const STATUS_BADGE_MAP = {
  complete: { label: 'complete',            bg: '#f0fdf4', color: '#16a34a', border: '#bbf7d0' },
  approved: { label: 'complete (approved)', bg: '#dcfce7', color: '#15803d', border: '#86efac' },
  na:       { label: 'N/A',                 bg: 'var(--gw-bone)', color: 'var(--gw-mist)', border: 'var(--gw-border)' },
}

export const ACTION_BADGE_MAP = {
  upload: { label: 'Upload',    bg: '#eff6ff', color: '#1d4ed8', border: '#bfdbfe' },
  forms:  { label: 'Use forms', bg: '#f5f3ff', color: '#6d28d9', border: '#ddd6fe' },
  sign:   { label: 'Sign',      bg: '#fff7ed', color: '#c2410c', border: '#fed7aa' },
}

export const DEFAULT_KEY_DATE_TYPES = [
  'Closing', 'Financing Contingency', 'Inspection', 'HUD Approval', 'Appraisal', 'Lease Start Date', 'Possession Date',
]
