// Your account & settings, and the office-admin guides — written from
// Integrations.jsx, Settings.jsx, Team/*, Messages.jsx, InstallPrompt,
// NotificationBell, Reports.jsx, AdminReview.jsx, the commission back office
// and RoundRobinPanel. **Bold** text is the exact on-screen label.

export default [
  {
    id: 'connect-outlook',
    category: 'account',
    title: 'Connect your Outlook email and calendar',
    summary: 'Connect Microsoft 365 once to send email from the CRM, put key dates on your calendar and run drips and mass emails.',
    minutes: 2,
    keywords: ['outlook', 'microsoft', '365', 'office 365', 'email', 'calendar', 'connect', 'reconnect', 'integration'],
    routes: ['integrations'],
    action: { label: 'Open Integrations', route: 'integrations' },
    steps: [
      { title: 'Open Integrations', body: 'Click **Integrations** at the bottom of the left menu. (On a phone: **More**, then **Integrations**.)' },
      { title: 'Connect', body: 'On the **Microsoft Outlook** card, click **Connect Outlook**.' },
      { title: 'Sign in to Microsoft', body: 'Sign in with your work Microsoft account and click **Accept** to approve access to mail, calendar and contacts.' },
      { title: 'You’re back', body: 'You return to the CRM with “Outlook connected”. The card shows **Connected** and **Signed in as** your name.' },
    ],
    troubleshooting: [
      { problem: 'It says “Needs reconnect”', fix: 'Your Microsoft sign-in expired. Click **Reconnect** and sign in again.' },
      { problem: '“This connection attempt expired — please try again”', fix: 'Click **Connect Outlook** again and finish the Microsoft sign-in without waiting too long.' },
      { problem: 'What does connecting turn on?', fix: 'Sending email from the CRM (and keeping it on the contact), the contact **Emails** tab, **Mass Email**, **Drip Sequences**, tasks and key dates on your calendar, and **Fill from address book** on contacts.' },
    ],
    related: ['call-text-email', 'mass-email', 'drip-sequence'],
  },
  {
    id: 'edit-profile',
    category: 'account',
    title: 'Update your profile, photo and email signature',
    summary: 'Your headshot, bio and contact details appear on your landing pages and advisor profile — and you can copy an email signature.',
    minutes: 4,
    keywords: ['profile', 'photo', 'headshot', 'bio', 'signature', 'email signature', 'name', 'phone', 'tagline'],
    routes: ['team', 'settings'],
    action: { label: 'Open Team', route: 'team' },
    steps: [
      { title: 'Open your profile', body: 'Click **Team** in the left menu. On your own card (marked “● Active”), click the pencil — **Edit your profile**.' },
      { title: 'Add your photo', body: 'Click **Upload headshot**. It shows on your QR landing pages.' },
      { title: 'Update your details', body: 'Check **Full Name**, **Email** and **Phone**, and add a **Tagline** and **Bio** (up to 600 characters) for your advisor profile.' },
      { title: 'Save', body: 'Click **Save Agent**. You’ll see “Profile updated”.' },
      { title: 'Copy your email signature', body: 'Under **Shareable profile**, click **Copy email-signature HTML** and paste it into your Outlook or Gmail signature settings. **Copy link** copies your profile page link.', tip: 'Save first, so the signature includes your latest changes.' },
    ],
    troubleshooting: [
      { problem: 'I can’t change my role or title', fix: 'Only an office admin can change those.' },
      { problem: 'My split and cap are wrong', fix: 'They’re shown read-only on your profile. Ask your office admin to correct them.' },
      { problem: 'I can’t find Team in the menu', fix: 'You may have hidden it. Go to **Settings** → **Customize My Sidebar** and turn it back on.' },
    ],
    related: ['customize-sidebar'],
  },
  {
    id: 'customize-sidebar',
    category: 'account',
    title: 'Hide menu items you don’t use',
    summary: 'Tidy your sidebar by hiding sections you don’t need — you can bring them back any time.',
    minutes: 1,
    keywords: ['sidebar', 'menu', 'hide', 'show', 'customize', 'navigation', 'settings', 'missing menu item'],
    routes: ['settings'],
    action: { label: 'Open Settings', route: 'settings' },
    steps: [
      { title: 'Open Settings', body: 'Click **Settings** at the bottom of the left menu.' },
      { title: 'Choose what to hide', body: 'Under **Customize My Sidebar**, click an item to hide it (it turns grey and crossed out). Click it again to show it.' },
      { title: 'Save', body: 'Click **Save Sidebar Preferences**. **Show all** turns everything back on — then save.' },
    ],
    troubleshooting: [
      { problem: 'A page I need has vanished', fix: 'It’s probably hidden here. Dashboard, Pipeline, Settings, Integrations and Help can’t be hidden.' },
      { problem: 'Messages won’t appear', fix: 'Messages only shows once your office has given you a texting number.' },
    ],
    related: ['edit-profile'],
  },
  {
    id: 'messages-sms',
    category: 'account',
    title: 'Text clients from the Messages inbox',
    summary: 'Two-way texting from your own business number — replies appear in the CRM as they arrive.',
    minutes: 2,
    keywords: ['text', 'sms', 'messages', 'twilio', 'inbox', 'reply'],
    routes: ['messages'],
    action: { label: 'Open Messages', route: 'messages' },
    before: ['Your office has set up a texting number for you. Until then, **Messages** doesn’t appear in your menu.'],
    steps: [
      { title: 'Open Messages', body: 'Click **Messages** in the left menu. Conversations are on the left; a red badge shows unread ones.' },
      { title: 'Open a conversation', body: 'Click it. Threads from a number in your contacts show **Linked contact**.' },
      { title: 'Reply', body: 'Type in the box and press Enter (Shift+Enter for a new line).' },
    ],
    troubleshooting: [
      { problem: 'How do I start a new text?', fix: 'A conversation appears when a client texts your number first. To text someone new, use **Text** on their contact (that opens your phone’s own messages app and isn’t kept in the CRM).' },
      { problem: '“No sending number assigned to your profile”', fix: 'Ask your office admin to set up your texting number.' },
    ],
    related: ['call-text-email'],
  },
  {
    id: 'install-app',
    category: 'account',
    title: 'Install the CRM on your phone or computer',
    summary: 'Add the CRM to your home screen so it opens like an app, full screen, in one tap.',
    minutes: 1,
    keywords: ['install', 'app', 'phone', 'iphone', 'android', 'home screen', 'mobile', 'desktop app'],
    routes: ['dashboard'],
    steps: [
      { title: 'On an iPhone or iPad', body: 'Open the CRM in **Safari**. Tap the **Share** button, then **Add to Home Screen**, then **Add**. Open it from the new icon and sign in once more.' },
      { title: 'On Android or a computer (Chrome or Edge)', body: 'Look for the **Install Gateway CRM** card at the bottom right and tap **Install** — or use the install icon in the browser’s address bar.' },
      { title: 'Updates', body: 'The installed app updates itself — there’s nothing to download from an app store.' },
    ],
    troubleshooting: [
      { problem: 'I closed the install card', fix: 'It comes back after 30 days. You can still install from the browser menu any time.' },
      { problem: 'There’s no install option on my Mac', fix: 'Safari and Firefox on a computer don’t offer it. Open the CRM in Chrome or Edge.' },
    ],
  },
  {
    id: 'notifications',
    category: 'account',
    title: 'Notifications: what the bell tells you',
    summary: 'New website leads, key-date reminders, signed documents and deals needing attention.',
    minutes: 1,
    keywords: ['notifications', 'bell', 'alerts', 'reminders', 'unread', 'mark read'],
    routes: ['dashboard'],
    steps: [
      { title: 'Check the bell', body: 'The bell at the top right shows a red count of unread notifications. Click it to see them.' },
      { title: 'What you’ll get', body: 'New website leads, key dates coming up (3 days, tomorrow, today), documents signed, declined or expired, deals closing soon with checklist items open, deals gone quiet, and colleagues asking to join your deal.' },
      { title: 'Clear them', body: 'Click a notification to open its deal, the × to dismiss it, or **Mark all read**. Read notifications disappear.' },
    ],
    related: ['website-leads', 'deal-tabs', 'track-signatures'],
  },
  {
    id: 'reports',
    category: 'account',
    title: 'Read your reports',
    summary: 'Where your leads come from, how long deals sit in each stage, which deals are stuck, and close rates.',
    minutes: 3,
    keywords: ['reports', 'analytics', 'roi', 'lead source', 'conversion', 'stuck deals', 'velocity', 'funnel', 'performance'],
    routes: ['reports'],
    action: { label: 'Open Reports', route: 'reports' },
    steps: [
      { title: 'Open Reports', body: 'Click **Reports** in the left menu. You see your own numbers; office admins see the firm.' },
      { title: 'Stuck Deals — start here', body: 'Deals idle longer than usual for their stage. Click **Open** to work each one.' },
      { title: 'Pipeline Velocity', body: 'How many days deals usually sit in each stage. A red bar means more than 21 days.' },
      { title: 'Lead Source ROI', body: 'Contacts, closed deals and estimated earnings by lead source — fill in **Source** on your contacts to make this useful.' },
      { title: 'Agent Performance and Pipeline Funnel', body: 'Close rates, average deal size and time to close, and how deals spread across stages.' },
    ],
    related: ['add-contact', 'move-deal'],
  },

  // ── Office admin ─────────────────────────────────────────────────────────
  {
    id: 'review-queue',
    category: 'office',
    adminOnly: true,
    title: 'Approve deals for closing',
    summary: 'Review deals agents submit before closing — approve them or request changes.',
    minutes: 3,
    keywords: ['review queue', 'approve', 'closing review', 'compliance', 'request changes', 'admin'],
    routes: ['review', 'pipeline'],
    action: { label: 'Open Review Queue', route: 'review' },
    steps: [
      { title: 'Open the Review Queue', body: 'Click **Review Queue** in the left menu. **Awaiting Review** lists deals submitted for closing.' },
      { title: 'Check the deal', body: 'Expand a row to see its compliance status and the agent’s notes. **Open deal →** opens the full deal.' },
      { title: 'Decide', body: 'Click **Approve for closing**, or **Request changes** and write what needs fixing (notes are required). The agent is notified.' },
      { title: 'Closing packet', body: 'On an approved deal’s page, the **Closing Packet** card’s **Generate** merges the deal’s documents into one packet.' },
    ],
    related: ['close-deal', 'back-office'],
  },
  {
    id: 'back-office',
    category: 'office',
    adminOnly: true,
    title: 'Manage commission splits and agent caps',
    summary: 'Edit each deal’s split, set every agent’s split, fee and cap, confirm caps and export the brokerage report.',
    minutes: 5,
    keywords: ['back office', 'commission', 'split', 'cap', 'transaction fee', 'brokerage report', 'export', 'admin'],
    routes: ['commission'],
    action: { label: 'Open Back Office', route: 'commission' },
    steps: [
      { title: 'Open the Back Office', body: 'Click **Commission** in the left menu. Office admins see the **Back Office** with three tabs.' },
      { title: 'Tracker — each deal', body: 'Filter by stage, type or agent. Click the pencil (**Edit splits**) on a deal to set who splits it and how, then save.' },
      { title: 'Agents & Caps — each agent', body: 'Set **Default Split %**, **Fee per Deal ($)**, **Cap Amount ($)** and **Cap Anniversary**, then **Save**.' },
      { title: 'Confirm caps', body: 'When an agent reaches their cap, click **Review & confirm** (or **Confirm cap met**). They keep 100% from that day until their cap date.' },
      { title: 'Brokerage Report', body: 'Pick a period and click **Export CSV** for volume, GCI, agent take, house split and fees per agent.' },
    ],
    related: ['commission', 'review-queue'],
  },
  {
    id: 'lead-rotation',
    category: 'office',
    adminOnly: true,
    title: 'Manage the website lead rotation',
    summary: 'Choose which agents get website leads, in what order, in each lane.',
    minutes: 2,
    keywords: ['round robin', 'rotation', 'lead distribution', 'website leads', 'lanes', 'admin'],
    routes: ['leads'],
    action: { label: 'Open Website Leads', route: 'leads' },
    steps: [
      { title: 'Open the rotation', body: 'In **Website Leads**, click the **Round Robin** tab. There are two lanes: **Residential** and **Commercial**.' },
      { title: 'Add or remove agents', body: 'Use **+ Add an agent to …** to add someone, and × to remove them.' },
      { title: 'Change the order', body: 'Use the up and down arrows. “Next up” shows who gets the next lead.' },
      { title: 'Pause someone', body: 'Click **Pause** while an agent is away — they’re skipped until you click **Resume**.' },
    ],
    related: ['website-leads'],
  },
  {
    id: 'team-admin',
    category: 'office',
    adminOnly: true,
    title: 'Add agents and teams',
    summary: 'Add an agent to the roster, set their split and cap, and group agents into teams.',
    minutes: 4,
    keywords: ['add agent', 'roster', 'team', 'new hire', 'split', 'cap', 'switch to', 'view as', 'admin'],
    routes: ['team'],
    action: { label: 'Open Team', route: 'team' },
    steps: [
      { title: 'Add an agent', body: 'On **Team**, click **Add Agent**. Fill in their name, email and phone, and their commission split, fee per deal and cap. Save.' },
      { title: 'Create a team', body: 'Click **New Team**, add members and their splits (they must add up to 100%).' },
      { title: 'See the CRM as an agent', body: '**Switch to** on an agent’s card shows the app as that agent sees it (their menu and notifications). Reload the page to switch back.' },
    ],
    troubleshooting: [
      { problem: '“Member splits total …% — they must add up to 100%”', fix: 'Adjust the team members’ percentages so they total exactly 100.' },
    ],
    related: ['back-office', 'edit-profile'],
  },
]
