// Getting started, contacts and tasks — written from Contacts.jsx and
// pages/Contacts/*, Tasks.jsx, QuickAdd.jsx, Dashboard/TodayCard and
// GlobalSearch. **Bold** text is the exact on-screen label.

export default [
  {
    id: 'first-day',
    category: 'getting-started',
    title: 'Your first day in the CRM',
    summary: 'The four things to set up first, in order — from an empty CRM to your first deal.',
    minutes: 10,
    keywords: ['new agent', 'onboarding', 'start', 'setup', 'begin', 'welcome', 'getting started'],
    routes: ['dashboard'],
    action: { label: 'Open Dashboard', route: 'dashboard' },
    steps: [
      { title: 'Connect Outlook', body: 'So you can email clients from the CRM and get deal dates on your calendar. See **Connect your Outlook email and calendar**.' },
      { title: 'Add a contact', body: 'Add a client, prospect or owner you’re working with. See **Add a contact** — or bring in your whole list with **Import contacts from a spreadsheet**.' },
      { title: 'Add a property', body: 'Add the listing or building you’re working on. See **Add a property or listing**.' },
      { title: 'Start a deal', body: 'Create the deal, link the client and the property, and it appears on your Pipeline. See **Create a deal**.' },
      { title: 'Follow the Getting started card', body: 'New agents see a **Getting started** card on the Dashboard with these same steps. Each one has a button that opens the right screen, and it ticks itself off as you go.', tip: 'You can hide the card with the **×** in its corner. It only hides it on this device.' },
    ],
    related: ['connect-outlook', 'add-contact', 'add-property', 'create-deal'],
  },
  {
    id: 'find-anything',
    category: 'getting-started',
    title: 'Find any contact, property or deal',
    summary: 'The search box at the top of every screen finds people, properties and deals as you type.',
    minutes: 1,
    keywords: ['search', 'find', 'look up', 'ctrl k', 'cmd k', 'shortcut'],
    routes: ['dashboard', 'contacts', 'properties', 'pipeline'],
    steps: [
      { title: 'Click the search box', body: 'It’s at the top of every screen and says **Search contacts, properties, deals…**. Shortcut: **Ctrl+K** on Windows, **⌘K** on a Mac.' },
      { title: 'Type at least two letters', body: 'Contacts match on name, email, phone or city. Properties match on address, unit, city or MLS number. Deals match on title and notes.', tip: 'For a phone number, type 3 or more digits — “515-555” works.' },
      { title: 'Open the result', body: 'Click it, or use the arrow keys and press Enter. A contact opens in its panel; a deal opens its deal page. Press Esc to close the search.' },
    ],
    troubleshooting: [
      { problem: 'Someone I know is in the CRM doesn’t come up', fix: 'You only see contacts in your own book (plus teammates who share with you and people on your deals). If it was reassigned to another agent, you won’t see it.' },
      { problem: 'Searching by tag finds nothing', fix: 'The top search doesn’t look at tags. Use the search box on the **Contacts** page instead — that one does.' },
    ],
    related: ['add-contact', 'edit-contact'],
  },
  {
    id: 'add-contact',
    category: 'contacts',
    title: 'Add a contact',
    summary: 'Add a client, prospect or property owner — with their details, type and buyer or seller criteria.',
    minutes: 2,
    keywords: ['new contact', 'create contact', 'client', 'lead', 'buyer', 'seller', 'person', 'add person'],
    routes: ['contacts', 'dashboard'],
    action: { label: 'Add a contact now', route: 'contacts', startNew: 'contact' },
    steps: [
      { title: 'Open a blank contact', body: 'On **Contacts**, click **Add Contact** (or press **n**). From the Dashboard, click **+ Contact**.', tip: 'Office admins don’t have Contacts in the sidebar — use **+ Contact** on the Dashboard or the search box.' },
      { title: 'Fill in the name', body: '**First Name** and **Last Name** are required. Add **Email** and **Phone** — you’ll need an email to send them anything.' },
      { title: 'Set type, status and source', body: 'Choose the **Type** (Buyer, Seller, Landlord, Tenant or Investor), the **Status** and where they came from under **Source**. Source feeds the lead-source report.' },
      { title: 'Add what they’re looking for', body: 'For a Buyer or Investor, fill in the criteria card (asset types, submarkets, size, budget). For a Seller or Landlord, the property profile. These drive Mass Email audiences and buyer matching — all optional.' },
      { title: 'Optional extras', body: 'Add **Tags**, **Birthday**, **Closing Anniversary**, a spouse or partner (**+ Add spouse / partner**) and **Notes**. Tick **Exclude from mass emails** for someone who should only hear from you one-to-one.' },
      { title: 'Save', body: 'Click **Save Contact**. You’ll see “Contact added”, and they appear at the top of your list.' },
    ],
    troubleshooting: [
      { problem: '“Possible duplicate”', fix: 'Someone in your book already has that email or phone. Open them instead — or, if it really is a different person, click **Save anyway**.' },
      { problem: 'The Last Name box turned red but says nothing', fix: 'Last name is required. Type it in and save again.' },
      { problem: '“Saving hands this contact to …”', fix: 'You picked a different **Assigned Agent**. Saving moves the contact into their book, and you may no longer see it. Change it back to yourself if that wasn’t intended.' },
      { problem: 'I just need to jot someone down quickly', fix: 'Use the round **+** button at the bottom right, then **New Contact**. It asks for less — you can fill in the rest later.' },
    ],
    related: ['import-contacts', 'edit-contact', 'log-activity'],
  },
  {
    id: 'import-contacts',
    category: 'contacts',
    title: 'Import contacts from a spreadsheet',
    summary: 'Bring a whole list in at once from a CSV file — with duplicate checking.',
    minutes: 5,
    keywords: ['import', 'csv', 'excel', 'spreadsheet', 'upload contacts', 'bulk add', 'list'],
    routes: ['contacts'],
    action: { label: 'Open Contacts', route: 'contacts' },
    before: [
      'Save your spreadsheet as a **CSV** file (in Excel: File → Save As → CSV). The first row must be the column headings.',
      'Avoid line breaks inside a cell — they break the row in two.',
    ],
    steps: [
      { title: 'Open the importer', body: 'On **Contacts**, click **Import CSV**.' },
      { title: 'Choose your file', body: 'Drop the file on the box, or click it to browse.' },
      { title: 'Match your columns', body: 'For each CRM field (**First Name**, **Last Name**, **Email**, **Phone**, **Type**, **Source**, **Status**, **Notes**, **Agent Name**), pick the matching column in your file. Common headings like “First Name” are matched for you.', tip: 'Columns named “Agent Name”, “E-mail” or “Phone Number” aren’t matched automatically — pick them by hand.' },
      { title: 'Choose the default agent', body: 'Contacts with no agent column go to the **Default Agent**. Leave **Skip duplicates** ticked so people already in your book aren’t added twice.' },
      { title: 'Preview and import', body: 'Click **Preview →**. Check the first rows and the counts (how many will be imported, how many skipped), then click **Import … Contacts**.' },
    ],
    troubleshooting: [
      { problem: 'Preview is greyed out', fix: 'Map the **First Name** column — it’s the one field the import needs.' },
      { problem: 'Everyone came in as “buyer”', fix: 'Type, Source and Status must use the CRM’s own words (for example “seller”, “referral”, “cold”). Anything else falls back to buyer / other / active. Fix the cells in your file, or update the contacts afterwards.' },
      { problem: 'It stopped part way with an error', fix: 'Rows before the error were saved. Reload the page before importing the rest, so the duplicate check sees what already came in.' },
      { problem: 'Tags, addresses or birthdays are missing', fix: 'The importer doesn’t bring those in. Add them on each contact afterwards.' },
    ],
    related: ['add-contact', 'bulk-contacts'],
  },
  {
    id: 'edit-contact',
    category: 'contacts',
    title: 'Update a contact, change the agent, add tags',
    summary: 'Edit details, hand a contact to another agent, tag them, and filter your list.',
    minutes: 2,
    keywords: ['edit contact', 'change agent', 'reassign', 'tag', 'tags', 'status', 'heat', 'hot', 'filter', 'saved views'],
    routes: ['contacts'],
    action: { label: 'Open Contacts', route: 'contacts' },
    steps: [
      { title: 'Open the contact', body: 'Click their row (or search for them). The panel opens on the **Activity** tab.' },
      { title: 'Go to Details', body: 'Click the **Details** tab, make your changes, and click **Save Contact**. You’ll see “Contact updated”.' },
      { title: 'Change the agent', body: 'Pick someone else under **Assigned Agent** and save. The contact moves to their book. On a computer you can also click the Agent cell in the list to change it straight away.' },
      { title: 'Tag them', body: 'Click **Tags**, pick an existing tag or type a new one and click **Add “…” as a new tag**. Click a tag to remove it.' },
      { title: 'Filter your list', body: 'Use the tabs (**Hot leads**, **Untouched 30+ days**, **New this week**…) and the **All Types / All Statuses / All Agents / All Heat** filters. **Clear** resets the filters and search.', tip: 'Heat (Hot, Warm, Cold) is worked out for you from recent activity and open deals — you can’t set it by hand.' },
    ],
    troubleshooting: [
      { problem: 'The contact disappeared after I changed the agent', fix: 'It moved to that agent’s book. Ask them, or an office admin, if it needs to come back.' },
      { problem: 'I can only pick Active, Cold or Closed in the list', fix: 'The list’s quick status menu is short on purpose. Open the contact’s **Details** for Lead, Opportunity and Pending.' },
      { problem: 'My filters are still on next time', fix: 'Filters and the selected tab are remembered between visits. Click **Clear**, and pick the **All** tab.' },
    ],
    related: ['bulk-contacts', 'log-activity', 'delete-contact'],
  },
  {
    id: 'log-activity',
    category: 'contacts',
    title: 'Log a call and set a follow-up',
    summary: 'Record calls, notes, emails, meetings and showings on a contact — and get a follow-up task in one step.',
    minutes: 1,
    keywords: ['log call', 'activity', 'note', 'follow up', 'follow-up', 'voicemail', 'timeline', 'history', 'outcome'],
    routes: ['contacts'],
    action: { label: 'Open Contacts', route: 'contacts' },
    steps: [
      { title: 'Open the contact', body: 'It opens on the **Activity** tab.' },
      { title: 'Choose the type', body: 'Pick **Call**, **Note**, **Email**, **Meeting** or **Showing**.' },
      { title: 'Pick a follow-up first (optional)', body: 'Set **Follow up** to **Tomorrow**, **In 3 days**, **In a week**… before you log. It creates a task “Follow up with …” at 9:00 AM (moved to Monday if it lands on a weekend).' },
      { title: 'Log it', body: 'For a call, tap an outcome — **No answer**, **Left voicemail**, **Spoke — interested** or **Spoke — not now** — and it’s logged straight away. Or type what happened and press Enter or **Log**.' },
    ],
    troubleshooting: [
      { problem: 'The contact still shows as untouched', fix: 'A **Note** doesn’t count as contact. Log it as a Call, Email, Meeting or Showing to update “Last Contact”.' },
      { problem: 'I logged something by mistake', fix: 'Logged activity can’t be edited or removed. Log a correcting note underneath it.' },
      { problem: '“Logged, but the follow-up wasn’t saved”', fix: 'Create the follow-up on the **Tasks** page by hand.' },
    ],
    related: ['call-text-email', 'tasks'],
  },
  {
    id: 'call-text-email',
    category: 'contacts',
    title: 'Call, text or email a contact',
    summary: 'One-tap call, text and email buttons at the top of every contact.',
    minutes: 2,
    keywords: ['call', 'phone', 'dial', 'text', 'sms', 'email contact', 'send email', 'outlook'],
    routes: ['contacts'],
    action: { label: 'Open Contacts', route: 'contacts' },
    steps: [
      { title: 'Open the contact', body: 'The buttons appear at the top once the contact is saved and has a phone or email.' },
      { title: 'Call', body: 'Tap **Call** — it opens your phone’s dialer and switches to the **Activity** tab so you can log how it went.' },
      { title: 'Text', body: 'Tap **Text** — it opens your phone’s own messages app. (These texts aren’t recorded in the CRM.)' },
      { title: 'Email', body: 'Tap **Email** to open the **Emails** tab. Click **New Email**, write your message and click **Send**. It goes from your own Outlook mailbox and is kept on the contact.' },
    ],
    troubleshooting: [
      { problem: '“Outlook isn’t connected”', fix: 'Connect it once under **Integrations**. See **Connect your Outlook email and calendar**.' },
      { problem: '“Outlook needs to be reconnected”', fix: 'Go to **Integrations** and click **Reconnect**.' },
    ],
    related: ['log-activity', 'connect-outlook', 'one-off-email'],
  },
  {
    id: 'tasks',
    category: 'contacts',
    title: 'Create and complete tasks',
    summary: 'Keep track of calls, showings and follow-ups — and see what’s due today.',
    minutes: 2,
    keywords: ['task', 'to do', 'todo', 'reminder', 'due', 'overdue', 'today', 'complete'],
    routes: ['tasks', 'dashboard'],
    action: { label: 'Open Tasks', route: 'tasks' },
    steps: [
      { title: 'Add a task', body: 'On **Tasks**, click **Add Task**. Give it a **Task Title**, then choose a **Type**, **Priority** and **Due Date**. Link a **Contact** or **Deal** if it’s about one.', tip: 'With Outlook connected, a task with a due date is added to your Outlook calendar.' },
      { title: 'Save', body: 'Click **Save Task**. Tasks are personal — only you see yours.' },
      { title: 'See what’s due', body: 'The Tasks page groups them into **Overdue**, **Today**, **This Week** and **Upcoming & Other**. The **Today** card on your Dashboard shows tasks due, new leads to call, and deals needing a look.' },
      { title: 'Complete it', body: 'Click the round checkbox beside the task (or the tick on the Dashboard). Tick **Show completed** to see finished ones; click again to reopen.' },
    ],
    troubleshooting: [
      { problem: 'The title box turned red', fix: 'Every task needs a title.' },
      { problem: 'Tasks I didn’t create appeared', fix: 'Moving a deal to a new stage, logging a follow-up, and setting a cold-call callback all create tasks for you automatically.' },
      { problem: 'I deleted a task by mistake', fix: 'Deleting can’t be undone — add it again.' },
    ],
    related: ['log-activity', 'move-deal'],
  },
  {
    id: 'bulk-contacts',
    category: 'contacts',
    title: 'Reassign, re-status or delete many contacts at once',
    summary: 'Select several contacts and act on all of them together (on a computer).',
    minutes: 1,
    keywords: ['bulk', 'select all', 'multiple', 'mass update', 'reassign many'],
    routes: ['contacts'],
    action: { label: 'Open Contacts', route: 'contacts' },
    steps: [
      { title: 'Select contacts', body: 'Tick the checkbox on each row, or the top checkbox to select everyone matching your current filters.' },
      { title: 'Choose an action', body: 'A dark bar appears at the bottom. Use **Reassign to…** then **Assign**, or **Set status…**, or **Delete**.' },
      { title: 'Finish', body: 'Click **Cancel** on the bar to clear the selection.' },
    ],
    troubleshooting: [
      { problem: 'I don’t see checkboxes', fix: 'Bulk actions are only on a computer — the phone layout hides them.' },
      { problem: 'Some selections vanished', fix: 'Changing the search or filters drops selected contacts that are no longer shown, so you never act on someone you can’t see.' },
    ],
    related: ['edit-contact', 'delete-contact'],
  },
  {
    id: 'delete-contact',
    category: 'contacts',
    title: 'Delete a contact (and undo it)',
    summary: 'Remove a contact — with an 8-second Undo if you change your mind.',
    minutes: 1,
    keywords: ['delete', 'remove contact', 'undo', 'restore'],
    routes: ['contacts'],
    action: { label: 'Open Contacts', route: 'contacts' },
    steps: [
      { title: 'Find the contact', body: 'On a computer, hover over their row in **Contacts**.' },
      { title: 'Delete', body: 'Click the trash icon at the end of the row, then **Delete** to confirm.' },
      { title: 'Changed your mind?', body: 'Click **Undo** on the message that appears. You have 8 seconds — hovering over the message pauses the countdown.' },
    ],
    troubleshooting: [
      { problem: 'There’s no delete button in the contact’s panel', fix: 'Delete from the list instead (on a computer). Phones can’t delete contacts.' },
    ],
    related: ['bulk-contacts'],
  },
]
