// Deals & the pipeline, plus the deal's Documents tab (split / merge / mark
// up) — written from pages/pipeline/*, pages/deal/*, DealPage.jsx, the PDF
// modals and lib/compliance.js. **Bold** text is the exact on-screen label.

const OPEN_DEAL = {
  title: 'Open the deal',
  body: 'Go to **Pipeline** and click the deal’s card. Its deal page opens; click **Edit Deal** for the tabs.',
}

export default [
  {
    id: 'create-deal',
    category: 'deals',
    title: 'Create a deal',
    summary: 'Start a deal, link the client and property, and choose which side you represent.',
    minutes: 3,
    keywords: ['new deal', 'transaction', 'start deal', 'add deal', 'buyer side', 'seller side', 'representing', 'co-agent'],
    routes: ['pipeline', 'dashboard'],
    action: { label: 'Start a deal now', route: 'pipeline', startNew: 'deal' },
    steps: [
      { title: 'Open a blank deal', body: 'On **Pipeline**, click **Add Deal** — or **Add deal** at the bottom of a column to start it in that stage. From the Dashboard, click **+ Deal**.', tip: 'Starting from a listing? Open the property and click **Start Deal**. It creates a seller-side deal with the address, price, owners and co-agents already filled in.' },
      { title: 'Name it', body: '**Deal Title** is required — for example “123 Main St Purchase”.' },
      { title: 'Choose the side', body: 'Under **Representing**, pick **Buyer**, **Seller** or **Both**. Choose **Residential** or **Commercial** under **Property Category**.' },
      { title: 'Link the people', body: 'Pick the **Buyer Contact** or **Seller Contact**, and add co-buyers or co-owners under **Additional … Contacts**. They’re filled in as signers when you send forms.' },
      { title: 'Link the property', body: 'Pick it under **Property**. The deal value and title fill in from it if they’re empty.' },
      { title: 'Value, stage and dates', body: 'Set the **Stage**, **Sale / Deal Value**, **Probability %** and **Expected Close Date**.' },
      { title: 'Agents and commission', body: '**Assigned Agent** defaults to you; add others under **Additional Agents**. Enter the commission rate or flat fee — see **Enter your commission**.' },
      { title: 'Save', body: 'Click **Save Deal**. You’ll see “Deal added”, and the deal page opens. The checklist fills itself in for the deal’s state.' },
    ],
    troubleshooting: [
      { problem: '“… already has an open … deal on this property”', fix: 'Another agent already has that side of this property. Ask to be added to their deal instead — documents and terms don’t carry between two separate deals.' },
      { problem: 'I don’t see Add Deal', fix: 'Office admins don’t get the Add Deal buttons on the board. Use **+ Deal** on the Dashboard.' },
      { problem: 'The tabs are missing', fix: 'A new deal only shows **Details** until it’s saved. Save it, then click **Edit Deal** on the deal page.' },
    ],
    related: ['move-deal', 'deal-tabs', 'commission', 'send-from-template'],
  },
  {
    id: 'move-deal',
    category: 'deals',
    title: 'Move a deal through the pipeline',
    summary: 'Drag deals between stages, switch between Board, List and Focus, and rename your columns.',
    minutes: 2,
    keywords: ['stage', 'move', 'drag', 'kanban', 'board', 'pipeline', 'focus', 'lost', 'rename column'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      { title: 'Open the board', body: 'Go to **Pipeline** and make sure **Transactions** and **Board** are selected.' },
      { title: 'Drag a card', body: 'Drag the deal to its new column: **Lead**, **Qualified**, **Showing**, **Offer**, **Under Contract** or **Lost**. Most moves create a next-step task for you, such as “Order inspection”.', tip: 'On the deal page you can also click a stage on the stage bar across the top.' },
      { title: 'Use List or Focus', body: '**List** is a sortable table. **Focus** shows only the deals that need you — overdue tasks, key dates coming up, and deals idle too long.' },
      { title: 'Rename a column', body: 'Double-click a column header (or click its pencil), type a name and press Enter. Only you see your names. **Reset headers** puts them back.' },
    ],
    troubleshooting: [
      { problem: 'Dropping on Closed didn’t close it', fix: 'Closing runs checks first. The deal page opens — see **Close a deal**.' },
      { problem: 'A card says “Idle”', fix: 'It has sat in its stage longer than usual. Plan the next step or move it on.' },
      { problem: 'The card jumped back', fix: 'The move didn’t save. Check your connection and try again.' },
    ],
    related: ['close-deal', 'tasks', 'deal-tabs'],
  },
  {
    id: 'deal-tabs',
    category: 'deals',
    title: 'Fill in deal terms, key dates and the checklist',
    summary: 'What each deal tab is for — terms that fill your forms, deadlines with reminders, and the transaction checklist.',
    minutes: 4,
    keywords: ['deal terms', 'key dates', 'closing date', 'inspection', 'deadline', 'checklist', 'earnest money', 'financing', 'reminder'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      OPEN_DEAL,
      { title: 'Deal Terms — fill in once', body: 'Enter earnest money, financing, deadlines, representation and listing details. Click **Save Deal Terms**. Every form you send for this deal fills itself in from here.' },
      { title: 'Key Dates — your deadlines', body: 'Set Closing, Inspection, Financing Contingency, Appraisal and so on. Add others with **+** or **+ Custom…**. Changes save on their own; you’ll get reminders 3 days, 1 day and on the day.', tip: 'With Outlook connected, key dates also go on the assigned agent’s calendar.' },
      { title: 'Checklist — what has to happen', body: 'It fills itself in for the deal’s state. Click an item’s box to cycle it through **complete**, **complete (approved)** and **N/A**. Add your own with **Add a document or step…**.' },
      { title: 'Client Portal — keep the client informed', body: 'Click **Enable Client Portal** and copy the link. Your client sees progress, key dates and any documents you share — no login needed.' },
    ],
    troubleshooting: [
      { problem: 'The checklist is empty', fix: 'Pick the deal’s **State** and type at the top of the Checklist tab and it fills in.' },
      { problem: 'An item doesn’t apply to this deal', fix: 'Click its status until it shows **N/A**. It no longer holds up closing — the office sees it listed as “Marked N/A” when it reviews the deal.' },
      { problem: 'My client can’t see a document in the portal', fix: 'Share it from the **Documents** tab: **⋯** → **Share with client portal**.' },
    ],
    related: ['deal-documents', 'close-deal', 'send-from-template'],
  },
  {
    id: 'deal-documents',
    category: 'documents',
    title: 'Upload and organise a deal’s documents',
    summary: 'Upload files to a deal, file them into the right pile, download them, and share them with your client.',
    minutes: 2,
    keywords: ['upload', 'documents', 'files', 'attach', 'pdf', 'download', 'file', 'share with client', 'required forms', 'quick look', 'preview', 'view'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      OPEN_DEAL,
      { title: 'Open the Documents tab', body: 'Click the **Documents** tab.' },
      { title: 'Upload', body: 'Drop a file on **Drop a file or click to upload** (PDF, Word or images, up to 50 MB).' },
      { title: 'File it', body: 'Files are sorted into piles like **Offers & purchase** or **Disclosures** from their name. To move one, click **⋯** → **File as …**.' },
      { title: 'Take a quick look', body: 'Click a document’s name (or the eye icon) to preview it without downloading. Use the arrows — or ← and → on your keyboard — to flip through the deal’s documents, and **Split**, **Merge with…** or **Mark up…** right from the preview.', tip: 'Merging and sending your own PDF for signature have the same eye icon, so you can check a file before you pick it.' },
      { title: 'Download or share', body: 'Click **⋯** → **Download**. To show a file in the client portal, click **⋯** → **Share with client portal**.' },
      { title: 'Need blank state forms?', body: 'Open **Required Forms** at the top of the tab, enter the state and type, and click **Find Forms**.' },
    ],
    troubleshooting: [
      { problem: '“File must be under 50 MB”', fix: 'Split the PDF into smaller parts first — see **Split a PDF into separate documents**.' },
      { problem: 'I deleted a file by mistake', fix: 'Deleting a document can’t be undone, and there’s no confirmation. Upload it again.' },
    ],
    related: ['split-documents', 'merge-documents', 'markup-document', 'signed-copies'],
  },
  {
    id: 'split-documents',
    category: 'documents',
    title: 'Split a PDF into separate documents',
    summary: 'Turn one scanned packet into separate files by page range. The original stays as it is.',
    minutes: 3,
    keywords: ['split', 'separate', 'pages', 'break up', 'extract pages', 'pdf', 'scan'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      OPEN_DEAL,
      { title: 'Click Split on the PDF', body: 'On the **Documents** tab, click **Split** on the PDF’s row.' },
      { title: 'Page through it', body: 'Use the page arrows and zoom on the left to see where each document starts and ends.' },
      { title: 'Enter the page ranges', body: 'On the right, fill in **From**, **To** and an optional **Document name** for each piece. Double-click From or To to drop in the page you’re looking at. Use **add line** for more pieces.' },
      { title: 'Check the preview', body: 'It lists what will be added to the deal, and notes any pages left out.' },
      { title: 'Split', body: 'Click **Split**. The new documents are added to the deal, and the original is kept.' },
    ],
    troubleshooting: [
      { problem: '“page A comes after page B — swap them”', fix: 'The **From** page must be before the **To** page on that line.' },
      { problem: '“this document only has … pages”', fix: 'A page number is past the end of the file. Check the last page number.' },
    ],
    related: ['merge-documents', 'deal-documents'],
  },
  {
    id: 'merge-documents',
    category: 'documents',
    title: 'Merge documents into one PDF',
    summary: 'Combine several PDFs into one, in the order you choose. The originals are kept.',
    minutes: 2,
    keywords: ['merge', 'combine', 'join', 'one pdf', 'pdf', 'packet', 'stitch'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      OPEN_DEAL,
      { title: 'Start from the first PDF', body: 'On the **Documents** tab, click **⋯** on the first PDF → **Merge with…**.' },
      { title: 'Add the others', body: 'Click **add document** and pick another PDF from the deal — or **Upload a PDF from this computer…**.' },
      { title: 'Put them in order', body: 'Drag the rows (≡) or use the up and down arrows. Remove one with its ×.' },
      { title: 'Name it and merge', body: 'Change the **Merged document name** if you like, then click **Merge**. The new PDF is saved to the deal.' },
    ],
    troubleshooting: [
      { problem: '“Add a second document — a merge needs at least two”', fix: 'Add at least one more PDF before merging.' },
      { problem: '“… is not a PDF, so it cannot be merged”', fix: 'Remove that file, convert it to PDF, and add it again.' },
      { problem: 'I want to merge signed forms for the MLS', fix: 'Use **Pack for MLS** on the Signatures tab — see **Get the signed copy**.' },
    ],
    related: ['split-documents', 'deal-documents', 'signed-copies'],
  },
  {
    id: 'markup-document',
    category: 'documents',
    title: 'Strike out text on a PDF before it’s signed',
    summary: 'Draw strike-through lines over wording you’re removing, saved as a new copy of the form.',
    minutes: 2,
    keywords: ['mark up', 'markup', 'strike', 'strikethrough', 'cross out', 'redline', 'edit pdf'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      OPEN_DEAL,
      { title: 'Open Mark up', body: 'On the **Documents** tab, click **⋯** on the PDF → **Mark up…**. (When sending your own PDF for signature you can also click **Mark up** there.)' },
      { title: 'Select the text to strike', body: 'Drag across the words with your mouse and let go — a line is drawn through them. They’re listed on the right under **Struck passages**; remove one with its ×.' },
      { title: 'Save', body: 'Check the **Save as** name and click **Save marked-up copy**. The original stays on the deal untouched.' },
    ],
    troubleshooting: [
      { problem: '“This page is a scan — no text to select”', fix: 'Scanned pages have no text to select, so they can’t be marked up here.' },
      { problem: '“Page … is rotated”', fix: 'Straighten the page first. Splitting and merging the PDF rewrites it upright.' },
      { problem: 'The form is already out for signature', fix: 'Don’t mark it up. Use **Add acknowledgement** on the Signatures tab so the client initials the change.' },
    ],
    related: ['upload-pdf-for-signature', 'track-signatures'],
  },
  {
    id: 'commission',
    category: 'deals',
    title: 'Enter your commission and see your earnings',
    summary: 'Enter the commission on a deal, see your take-home estimate, and track earnings and your cap.',
    minutes: 3,
    keywords: ['commission', 'split', 'cap', 'earnings', 'take home', 'pay', 'transaction fee', 'gci'],
    routes: ['pipeline', 'commission'],
    action: { label: 'Open My Earnings', route: 'commission' },
    steps: [
      OPEN_DEAL,
      { title: 'Enter the commission', body: 'On **Details**, find **Commission** for your side. Choose **Percentage** or **Flat Fee**, and enter the rate (for example 3) or the amount. With both sides, enter each side.' },
      { title: 'Read the estimate', body: 'The box shows **You take home $…** after your split and the transaction fee. It’s an estimate — the office confirms the final split.' },
      { title: 'See your earnings', body: 'Open **Commission** in the sidebar for **My Earnings**: earned this cap year, deals closed, projected from open deals, a month-by-month chart, and your cap progress.' },
    ],
    troubleshooting: [
      { problem: 'What’s a split and a cap?', fix: 'Your **split** is the share of your commission you keep; the office keeps the rest. Your **cap** is the most you pay the office in a year. Once the office confirms you’ve reached it, you keep 100% (less the transaction fee) until your cap date.' },
      { problem: '“No cap configured”', fix: 'Ask your office admin to set up your cap.' },
      { problem: 'My earnings page is empty', fix: 'Enter the commission on each deal’s **Details** tab and your take-home appears.' },
    ],
    related: ['close-deal'],
  },
  {
    id: 'close-deal',
    category: 'deals',
    title: 'Close a deal',
    summary: 'Clear the closing checks, submit for office review, and mark the deal Closed.',
    minutes: 4,
    keywords: ['close', 'closing', 'closed', 'compliance', 'review', 'submit for review', 'approval', 'mark lost', 'reopen'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      { title: 'Get it to Under Contract', body: 'Move the deal to **Under Contract**. The deal page then shows what’s left before it can close.' },
      { title: 'Clear each item', body: 'The **Compliance** card lists what’s outstanding — checklist items, signatures, required state forms, key dates. Each has a **Fix** button that opens the right tab.' },
      { title: 'Submit for review', body: 'Click **Submit for admin review** (or **Submit for review** on the Compliance card). It then shows “Awaiting admin review”.' },
      { title: 'If changes are requested', body: 'Read the **Admin notes**, fix what’s asked, and click **Resubmit**.' },
      { title: 'Close it', body: 'When the card says all checks pass, click **Closed** on the stage bar at the top of the deal page.' },
    ],
    troubleshooting: [
      { problem: '“Cannot close: …”', fix: 'Something is still outstanding. Follow the **Fix** buttons on the Compliance card.' },
      { problem: 'The deal fell through', fix: 'Click **Mark Lost** on the deal page. **Reopen** brings it back to Lead.' },
      { problem: 'Ticking a step on the deal page — does the Checklist tab know?', fix: 'Yes. Ticking a step on the **Next Actions** card marks it complete on the **Checklist** tab too, and the other way round.' },
    ],
    related: ['deal-tabs', 'track-signatures', 'commission'],
  },
  {
    id: 'delete-deal',
    category: 'deals',
    title: 'Delete or drop a deal',
    summary: 'Mark a deal Lost, reopen it, or delete it for good.',
    minutes: 1,
    keywords: ['delete deal', 'remove', 'lost', 'archive', 'reopen', 'dead deal'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      { title: 'Usually: mark it Lost', body: 'On the deal page, click **Mark Lost** (or drag the card to **Lost**). Everything is kept, and **Reopen** brings it back.' },
      { title: 'To delete it for good', body: 'On the **Pipeline** board, click the trash icon on the card, then **Delete**. This can’t be undone.' },
    ],
    related: ['move-deal'],
  },
]
