// Documents & e-signatures — written from the Signatures tab, the BoldSign
// modals and the Form Library (src/pages/deal/signatures/*, FormLibrary.jsx).
// Labels in **bold** are the exact words on screen; keep them in step with the UI.

const OPEN_SIGNATURES = {
  title: 'Open the deal’s Signatures tab',
  body: 'Go to **Pipeline** and click the deal. On the deal page, find the **Documents & Signatures** card and click **Send for signature**. (You can also click **Edit Deal** and choose the **Signatures** tab.)',
  tip: 'The Signatures tab only appears on a deal that has been saved. Create and save the deal first.',
}

export default [
  {
    id: 'send-from-template',
    category: 'documents',
    title: 'Send a document for e-signature (from a template)',
    summary: 'The fastest way to get a form signed: pick your state’s form, and the client, property and deal details fill in for you.',
    minutes: 5,
    keywords: ['boldsign', 'esign', 'e-sign', 'signature', 'docusign', 'sign', 'contract', 'agreement', 'buyer agency', 'listing agreement', 'send document'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    before: [
      'The deal is saved, and the client is linked to it as a contact — that is where the client’s name and email come from.',
      'Your office has set up the form as an e-sign template. If **Send from Template** is missing, ask your office admin.',
    ],
    steps: [
      OPEN_SIGNATURES,
      { title: 'Click Send from Template', body: 'Click **Send from Template** at the top of the tab. On a deal with nothing sent yet you can also click **Start: Send from Template**.' },
      { title: 'Pick the form', body: 'Choose it from the **Template** list. You see your state’s forms plus the general ones. Change the **Email Subject** if you want — it starts as “Please sign:” and the deal name.' },
      { title: 'Check the signers', body: 'Each role on the form (client, co-client, agent) is already filled in from the deal. Check every name and email. Start typing a name to pick someone from your contacts. Any role you leave blank is simply left off this send.', tip: 'If someone isn’t in your contacts yet, click **+ Save … to this deal’s contacts** under their row so the next form fills them in automatically.' },
      { title: 'Leave “Sign in this order” on', body: 'Keep **Sign in this order** ticked. Each signer then sees the lines filled in by the person before them. If you turn it off, your client may open the form with those lines blank.' },
      { title: 'Review the details from the deal', body: 'The section **From this deal — filled in automatically** shows what was copied in (buyer, agent, dates). Click **Review or edit shared fields** to change any of it. Under **Signer details** you can fill in anything else by hand.', tip: 'Fill values in on this screen — not on the field-placement screen. Anything typed there is only a preview and never reaches the signers.' },
      { title: 'Answer any required choices', body: 'Some forms have their own questions — for example **Representation** (Exclusive or Non-exclusive) on the buyer agency packet. You can’t continue until they are answered.' },
      { title: 'Optional: send options', body: 'Open **Send options** to change the **Note to the signers**, add people under **Send a copy to** (press Enter after each address), or set **Expires after** a number of days. These can only be set now, before the document is created.' },
      { title: 'Click Next: Review Draft', body: 'Nothing is sent yet. Click **Next: Review Draft** to see the filled-in form exactly as your signers will. You can **Download PDF** or **Print** it to go over with your client.' },
      { title: 'Send it', body: 'Click **Send for Signature**, check the list of people it will go to, then click **Send for Signature** again. You will see “Sent for signature — the signers have been notified.”' },
    ],
    troubleshooting: [
      { problem: 'There is no Send from Template button', fix: 'No e-sign template is set up for this deal’s state yet. Ask your office admin to add it in the **Form Library** — or use **Upload Your Own PDF** in the meantime.' },
      { problem: '“The client’s name will be blank in … places”', fix: 'The client isn’t linked to the deal. Add them as a contact on the deal (deal **Details**), or type the name into the highlighted fields.' },
      { problem: '“At least one signer needs a name and email”', fix: 'Fill in a name and a valid email address on at least one signer row.' },
      { problem: '“This form no longer matches the terms set up for it, so it can’t be sent”', fix: 'The form changed since your office set it up. Ask an admin to re-check it in the **Form Library**. Nothing was sent.' },
      { problem: 'I need to stop halfway', fix: 'Click **Save for Later**. Your work is kept on this form for this deal, and the filled draft appears on the Signatures tab. If you close without saving, you are asked whether to keep or discard your changes.' },
      { problem: 'The client wants a change after I sent it', fix: 'See **Track, remind and fix documents out for signature** — use **Add acknowledgement**, or **Recall** and send a corrected copy.' },
    ],
    related: ['track-signatures', 'upload-pdf-for-signature', 'send-forms-together', 'signed-copies'],
  },
  {
    id: 'upload-pdf-for-signature',
    category: 'documents',
    title: 'Send your own PDF for e-signature',
    summary: 'For a document that isn’t a template — an addendum, a lender form — upload it and place the signature boxes yourself.',
    minutes: 6,
    keywords: ['upload', 'pdf', 'boldsign', 'esign', 'signature', 'addendum', 'custom document', 'place fields'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    before: ['The file is a PDF. Convert Word documents to PDF first — only PDFs can be signed.'],
    steps: [
      OPEN_SIGNATURES,
      { title: 'Click Upload Your Own PDF', body: 'Click **Upload Your Own PDF** at the top of the tab.' },
      { title: 'Check the signers', body: 'The client from the deal is already listed. Click **+ Add another signer** for anyone else. Every signer needs a name and an email address.' },
      { title: 'Signing yourself?', body: 'Tick **I need to sign as well** if you also sign. You will sign after the client(s).' },
      { title: 'Choose the document', body: 'Pick a file the deal already has, or drop a PDF on the box (or click it to browse).', tip: 'Need to strike something out? Click **Mark up** first — the line is written into the PDF your client signs, and the marked-up copy is filed on the deal.' },
      { title: 'Click Continue in BoldSign', body: 'The signing editor opens inside the CRM. Drag a signature box and a date box onto the page for each signer.' },
      { title: 'Send from inside the editor', body: 'Click **Send** inside the editor. You will see “Sent for signature”, and the Signatures tab updates on its own as people sign.' },
    ],
    troubleshooting: [
      { problem: '“… is not a PDF”', fix: 'Save or export the file as a PDF and upload that.' },
      { problem: 'The file is too big', fix: 'The message tells you the limit. Split the PDF into two parts (see **Split a PDF into separate documents**) and send them separately.' },
      { problem: 'I closed the editor before sending', fix: 'It was kept as a draft. Find it on the Signatures tab under **Needs you** and click **Edit Fields** to carry on.' },
      { problem: '“Leave the editor?” warning', fix: 'Anything BoldSign hasn’t saved could be lost. Choose **Cancel**, click **Save** inside the editor, then close.' },
    ],
    related: ['send-from-template', 'split-documents', 'markup-document', 'track-signatures'],
  },
  {
    id: 'send-forms-together',
    category: 'documents',
    title: 'Send several forms together',
    summary: 'Send a packet of forms to the same people — as one signing session, or as separate requests.',
    minutes: 4,
    keywords: ['packet', 'multiple forms', 'bundle', 'several', 'together', 'esign'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    before: ['Your office has at least two e-sign templates set up. Otherwise this option doesn’t appear.'],
    steps: [
      OPEN_SIGNATURES,
      { title: 'Open the packet screen', body: 'Click **More**, then **Send several forms together…**.' },
      { title: 'Tick the forms', body: 'Tick each form you need. Use the up and down arrows to set their order.' },
      { title: 'Choose how to send', body: '**Together** makes one document and one signing session. **Separately** sends one request per form, so a declined form doesn’t hold up the others.' },
      { title: 'Fill in the signers', body: 'Check the name and email for each role. Leave **One at a time, in this order** ticked unless everyone may sign at once.' },
      { title: 'Send', body: 'For **Together**, click **Review & send**, check it, and click Send inside the editor. For **Separately**, click **Send for signature** — it goes immediately.' },
    ],
    troubleshooting: [
      { problem: 'Deal details aren’t filled in on the forms', fix: 'Packets only fill in the signers. If you need the deal’s details filled in, send each form with **Send from Template** instead.' },
      { problem: '“Check the roles”', fix: 'The forms you picked have different signer roles. Make sure each row has the right person, or send those forms separately.' },
      { problem: 'I want the signed forms as separate files later', fix: 'Choose **Separately**. A packet sent **Together** comes back as one combined PDF.' },
    ],
    related: ['send-from-template', 'track-signatures'],
  },
  {
    id: 'track-signatures',
    category: 'documents',
    title: 'Track, remind and fix documents out for signature',
    summary: 'See who still has to sign, nudge them, swap a signer, or recall a document and send a corrected copy.',
    minutes: 4,
    keywords: ['status', 'reminder', 'remind', 'nudge', 'recall', 'void', 'revoke', 'cancel', 'declined', 'expired', 'resend', 'correction', 'change signer', 'waiting'],
    routes: ['pipeline', 'dashboard'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      OPEN_SIGNATURES,
      { title: 'Read the groups', body: '**Needs you** holds drafts and anything stuck or out for a week or more. **Out for signature** is waiting on signers. **Recalled & declined** and **Signed** are collapsed underneath. Each row says who it’s waiting on and how many have signed (for example “1/2 signed”).' },
      { title: 'Remind the signers', body: 'Click **Remind** on the row. It only emails people who still have to sign, and only when it’s their turn. To chase one person, expand the row and click **Nudge** beside their name.', tip: 'The CRM also sends reminders on its own: after 3 days, every 3 days, up to 4 times.' },
      { title: 'Change a signer', body: 'Expand the row and click **Change** beside the person, then enter the new name and email and click **Change signer**. Signatures already collected stay in place.' },
      { title: 'Add a change the client asked for', body: 'Expand the row and click **Add acknowledgement**. Enter the page number and click **Add to packet**. The client initials the change when they sign.' },
      { title: 'Recall a document', body: 'Expand the row and click **Recall**, then **Recall** again to confirm. The signing link stops working for anyone who hasn’t finished. The document stays on the deal marked Revoked.' },
      { title: 'Send a corrected copy', body: 'On a declined, expired or recalled document, click **Send correction packet**. It keeps everything that was already filled in.' },
    ],
    troubleshooting: [
      { problem: '“BoldSign allows one manual reminder a day per document”', fix: 'This document was already reminded today. The automatic reminders will keep going — or call the client.' },
      { problem: 'A row says “Needs attention”', fix: 'Click **Fix packet** to reopen it and correct the problem.' },
      { problem: 'A row says “Applying a change…”', fix: 'A change is still going through. Wait a moment, then click **Check now**. Don’t send or edit until it finishes.' },
      { problem: 'Status looks out of date', fix: 'It normally updates on its own. Click **⋯** on the row and choose **Refresh status**.' },
    ],
    related: ['signature-queue', 'signed-copies', 'send-from-template'],
  },
  {
    id: 'signed-copies',
    category: 'documents',
    title: 'Get the signed copy',
    summary: 'Where fully signed documents end up, how to download them, and how to pack them for the MLS.',
    minutes: 2,
    keywords: ['download', 'signed pdf', 'completed', 'audit trail', 'mls', 'copy', 'executed'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      { title: 'It files itself', body: 'When everyone has signed you will see “Document fully signed — signed copy saved to Documents tab”. The signed PDF and its audit trail are saved to the deal’s **Documents** tab, and emailed to the agents on the deal.' },
      OPEN_SIGNATURES,
      { title: 'Download it', body: 'Open the **Signed** group, expand the document and click **Download Signed PDF**. **Audit Trail** downloads the record of who signed when.' },
      { title: 'Pack for the MLS', body: 'Click **Pack for MLS**, then **Download separately** or **Merge into one PDF**.' },
    ],
    troubleshooting: [
      { problem: '“That file is not available yet”', fix: 'The signed copy is still being saved. Try again in a minute.' },
      { problem: 'A change is needed after everyone signed', fix: 'Click **Send correction packet**. The original signed PDF stays on the deal.' },
    ],
    related: ['track-signatures', 'merge-documents', 'deal-documents'],
  },
  {
    id: 'signature-queue',
    category: 'documents',
    title: 'Chase unsigned documents from the Dashboard',
    summary: 'The Out for Signature card on your Dashboard lists everything waiting on a client, oldest first.',
    minutes: 1,
    keywords: ['dashboard', 'out for signature', 'waiting', 'queue', 'remind', 'unsigned'],
    routes: ['dashboard'],
    action: { label: 'Open Dashboard', route: 'dashboard' },
    steps: [
      { title: 'Find the card', body: 'On the **Dashboard**, the **Out for Signature** card shows when something is waiting. The count turns red when anything has waited a week or more.' },
      { title: 'Remind from the card', body: 'Each row shows who it’s waiting on and for how long. Click **Remind** to email whoever still has to sign.' },
      { title: 'Open the deal', body: 'Click a row to jump straight to that deal’s Signatures tab.' },
      { title: 'Don’t forget drafts', body: '**Prepared, not sent** lists documents you filled in but never sent. Open one and send it, or remove it.' },
    ],
    related: ['track-signatures', 'send-from-template'],
  },
  {
    id: 'form-library',
    category: 'documents',
    title: 'Find and download a blank form',
    summary: 'The Form Library has your state’s forms, ready to download and print.',
    minutes: 1,
    keywords: ['forms', 'state forms', 'blank', 'print', 'download', 'packet', 'iowa', 'nebraska', 'south dakota'],
    routes: ['form-library'],
    action: { label: 'Open Form Library', route: 'form-library' },
    steps: [
      { title: 'Open the Form Library', body: 'In the left menu, open **Marketing & Tools** and click **Form Library**.' },
      { title: 'Filter', body: 'Use **All States** and **All Types** (Buyer Contract, Listing / Seller, Lease / Rental, General / Other) to narrow the list. **Clear** resets them.' },
      { title: 'Download', body: 'Click **Get Forms** on the packet. One file downloads as a PDF; several come as a zip.' },
      { title: 'Want it signed electronically?', body: 'Don’t print it — open the deal’s **Signatures** tab and use **Send from Template**. Forms marked **Sendable** are available there, filled in from the deal.' },
    ],
    troubleshooting: [
      { problem: '“No file uploaded for this packet”', fix: 'Your office hasn’t uploaded the PDF yet. Ask your office admin.' },
      { problem: 'The form I need isn’t listed', fix: 'Ask your office admin to add it. Admins can add packets with **Add Packet**.' },
    ],
    related: ['send-from-template'],
  },
  {
    id: 'form-library-admin',
    category: 'office',
    adminOnly: true,
    title: 'Add a form to the Form Library',
    summary: 'Upload a state form packet so agents can download it — and switch it on for e-signature.',
    minutes: 5,
    keywords: ['admin', 'add packet', 'template', 'boldsign template', 'required to close'],
    routes: ['form-library'],
    action: { label: 'Open Form Library', route: 'form-library' },
    steps: [
      { title: 'Open the Form Library', body: 'Click **Form Library**, then **Add Packet**.' },
      { title: 'Describe it', body: 'Choose the **State** and **Transaction Type**, then give it a **Packet Name** and **Description**. Attach the PDF.' },
      { title: 'Make it sendable', body: 'To let agents send it for e-signature, add the signer roles and click **Build in BoldSign**. Leave **Active** on so it appears under **Send from Template**.' },
      { title: 'Required to close?', body: 'Tick **Required to close** if every deal of this type needs it. It is then shown as required.' },
      { title: 'Save', body: 'Save the packet. Use the pencil to edit it later, or the trash icon to delete it.' },
    ],
    related: ['form-library', 'send-from-template'],
  },
]
