// Email & marketing — written from MassEmail.jsx, AudienceFilter, BlastReport,
// Templates.jsx, Sequences.jsx, pages/campaigns/*, Leads.jsx and ColdCalls.jsx.
// **Bold** text is the exact on-screen label. Merge tokens differ per feature
// (Templates/Compose, Mass Email, Drips) — keep each guide's list to its own.

const OPEN_TOOLS = (item) =>
  `In the left menu, open **Marketing & Tools** (it may be folded up) and click **${item}**.`

export default [
  {
    id: 'mass-email',
    category: 'marketing',
    title: 'Send a mass email or deal announcement',
    summary: 'Announce a Just Closed, New Listing or Price Reduced deal — or a market update — to the right contacts, from your own mailbox.',
    minutes: 8,
    keywords: ['mass email', 'blast', 'newsletter', 'announcement', 'just closed', 'just sold', 'new listing', 'price reduced', 'market update', 'bulk email', 'email list'],
    routes: ['mass-email', 'properties'],
    action: { label: 'Open Mass Email', route: 'mass-email' },
    before: [
      'Outlook is connected — every email goes out from your own mailbox. See **Connect your Outlook email and calendar**.',
      'For a deal announcement, the property is in the CRM (ideally with photos).',
    ],
    steps: [
      { title: 'Open Mass Email', body: `${OPEN_TOOLS('Mass Email')} Or open a property and click **Announce** — it starts here with that property picked.` },
      { title: '1. Topic', body: 'Under **What are you sending?** choose **Just Closed**, **Under Contract**, **New Listing**, **Price Reduced**, **Coming Soon**, **Market Update** or **Other**. Pick the **Property** it’s about (not needed for a Market Update).' },
      { title: '2. Message', body: 'Start from the default wording or a saved template. Pick the photo, choose which **Details to include** (asset type, units, price, terms), and check the **Subject** and **Body**. The preview on the right shows exactly what a contact receives.', tip: 'Personalise with tokens such as {{firstName}}, {{propertyAddress}} and {{price}} — click the chips under the Body to insert them. If a first name is missing, {{firstName}} becomes “there”.' },
      { title: '3. Audience', body: 'Pick **Asset Types** and whether to **Match against** buyer criteria, seller criteria, or both. The count shows how many will receive it — click **Show contacts** to check, remove anyone with ×, or add someone with **Add someone the filter missed**. You can also paste or upload your own list.' },
      { title: '4. Review', body: 'Check the recipients, the property and **Sending as**. Click **Send to … recipients**, then **Send now**.' },
      { title: 'Let it finish', body: 'Messages go out about 30 a minute, so keep the page open for a large send. Each contact gets their own copy; nobody sees the rest of the list.' },
      { title: 'See how it did', body: 'Click **Past sends** at the top for opens, replies, unsubscribes and bounces. **Recipients** lists who did what.', tip: 'Opens are a floor, not a read receipt — most mail apps hide them.' },
    ],
    troubleshooting: [
      { problem: 'The Send button is greyed out', fix: 'Either Outlook isn’t connected (click **connect it in Integrations**) or nobody is selected yet.' },
      { problem: 'Someone I expected is under “Not receiving this send”', fix: 'Each person shows why — opted out of email, a closed contact, no email on file, or a duplicate. People who unsubscribed are never emailed.' },
      { problem: 'The send stopped part way', fix: 'Click **Resume — … left to send**. Nobody is emailed twice.' },
      { problem: '“the per-send limit is 500”', fix: 'Narrow the audience, or split the list and send in stages.' },
      { problem: '“Daily send limit reached”', fix: 'You can send 1,000 emails in 24 hours (drips count too). Resume tomorrow — nobody is mailed twice.' },
      { problem: 'Can I send a test or schedule it?', fix: 'Not yet — sends go out straight away. Check the preview on step 2 carefully before sending.' },
    ],
    related: ['email-templates', 'drip-sequence', 'connect-outlook', 'property-tools'],
  },
  {
    id: 'one-off-email',
    category: 'marketing',
    title: 'Email one contact',
    summary: 'Write and send a single email from your Outlook — from a contact, a deal, or a template.',
    minutes: 2,
    keywords: ['email', 'compose', 'send email', 'write email', 'ai', 'draft'],
    routes: ['contacts', 'templates', 'pipeline'],
    action: { label: 'Open Contacts', route: 'contacts' },
    steps: [
      { title: 'Open Compose', body: 'On **Contacts** (on a computer), hover over the person and click the envelope icon. On a deal page, click the email icon beside the client. Or on **Email Templates**, click **Compose**.' },
      { title: 'Write it', body: 'Check **To**, add a **Subject** and write the message. **✦ Write with AI** can draft it for you — always read it before sending.' },
      { title: 'Send', body: 'Click **Send via Outlook**. You can also **Save as Draft** to your Outlook drafts.' },
    ],
    troubleshooting: [
      { problem: '“Email sending not configured”', fix: 'Connect Outlook under **Integrations** (recommended), or ask your admin about a sending key in **Settings**.' },
      { problem: 'The button says “Open in Mail App”', fix: 'Nothing is connected, so it opens your computer’s mail program instead. Connect Outlook to send from the CRM.' },
    ],
    related: ['email-templates', 'call-text-email', 'connect-outlook'],
  },
  {
    id: 'email-templates',
    category: 'marketing',
    title: 'Create an email template',
    summary: 'Save wording you use often, with merge tags that fill in each contact’s details.',
    minutes: 3,
    keywords: ['template', 'email template', 'saved email', 'merge tag', 'canned', 'reuse'],
    routes: ['templates'],
    action: { label: 'Open Email Templates', route: 'templates' },
    steps: [
      { title: 'Open Email Templates', body: OPEN_TOOLS('Email Templates') },
      { title: 'Start a template', body: 'Click **+ New Template**. Give it a **Template Name** and **Subject Line** (both required), and pick a **Category**.', tip: 'Choose the **Deal Announcement** category to make it available in Mass Email.' },
      { title: 'Write the body', body: 'Type the message, or describe it under **AI Generate** and click **Generate**. Click a merge tag to insert it — {{firstName}}, {{lastName}}, {{agentName}}, {{propertyAddress}}, {{dealValue}}. **Preview** shows it with sample details.' },
      { title: 'Save', body: 'Click **Save Template**.' },
      { title: 'Use it', body: 'On the template’s card, click the send icon (**Use template**) to open it in Compose.' },
    ],
    troubleshooting: [
      { problem: 'A box turned red when I saved', fix: 'The **Template Name** and **Subject Line** are required.' },
      { problem: 'The contact’s name didn’t fill in', fix: 'Templates opened from **Use template** aren’t attached to a contact, so the name tags come out blank (first name shows as “there”). Check the message before sending.' },
    ],
    related: ['one-off-email', 'mass-email'],
  },
  {
    id: 'drip-sequence',
    category: 'marketing',
    title: 'Set up a drip sequence',
    summary: 'A series of emails and call reminders that goes out on a schedule after you enroll someone.',
    minutes: 6,
    keywords: ['drip', 'sequence', 'automation', 'nurture', 'follow up automatically', 'campaign', 'enroll'],
    routes: ['sequences'],
    action: { label: 'Open Drip Sequences', route: 'sequences' },
    before: ['Outlook is connected — drip emails send from your mailbox. Call steps still create tasks without it.'],
    steps: [
      { title: 'Open Drip Sequences', body: OPEN_TOOLS('Drip Sequences') },
      { title: 'Create one', body: 'Click **+ New Sequence**, name it and click **Create**. Or click **Starter: Buyer Lead** for a ready-made six-step sequence to edit.' },
      { title: 'Add steps', body: 'Click **+ Email** or **+ Call**. Set when each goes out — the first step is “Day 0” (immediately), later steps “Wait … days after the previous step”. Write the subject and message; click a token such as **+ First name** to personalise it.', tip: 'Use **Preview** on a step, and the preview menu to see it for a real contact.' },
      { title: 'Auto-start (optional)', body: 'Under **Auto-start for**, choose to start it automatically for residential or commercial website leads assigned to you.' },
      { title: 'Save', body: 'Click **Save** (it shows **Save*** while there are unsaved changes).' },
      { title: 'Enroll people', body: 'Click **Enroll**, tick contacts, and click **Enroll …**. The first step goes out right away; the rest go out once a day.' },
      { title: 'Pause or stop someone', body: 'Under **Enrolled**, change their status to **Paused** or **Stop**. Anyone who replies is taken out automatically.' },
    ],
    troubleshooting: [
      { problem: 'Enroll is greyed out', fix: 'Add at least one step and click **Save** first.' },
      { problem: '“… has no email address”', fix: 'That contact will skip email steps and stop at the first one. Add their email first.' },
      { problem: 'Emails aren’t going out', fix: 'Check the enrollment row for the reason — usually Outlook needs connecting or reconnecting under **Integrations**.' },
      { problem: 'I reordered steps and people got the wrong one', fix: 'People already enrolled keep their step number. Change steps before enrolling, where you can.' },
    ],
    related: ['email-templates', 'website-leads', 'connect-outlook'],
  },
  {
    id: 'mail-campaign',
    category: 'marketing',
    title: 'Create a mail campaign with QR tracking',
    summary: 'Track postcards, flyers and door hangers: a QR code on the piece leads to a landing page, and scans and leads are counted.',
    minutes: 8,
    keywords: ['mail campaign', 'postcard', 'flyer', 'door hanger', 'direct mail', 'qr', 'qr code', 'just sold', 'just listed', 'open house', 'farm', 'landing page', 'scan'],
    routes: ['campaigns'],
    action: { label: 'Open Mail Campaigns', route: 'campaigns' },
    steps: [
      { title: 'Open Mail Campaigns', body: 'Click **Mail Campaigns** in the left menu.' },
      { title: 'Pick a starting point', body: 'Under **Quick start**, click **Just Sold**, **Just Listed**, **Multifamily Farm** or **Open House** to pre-fill the form — or **Blank Mailing**. **+ New Mailing** also starts a blank one.' },
      { title: 'Fill in the mailing', body: 'Give it a **Mailing Name** (replace the [Address] placeholder), pick the **Mailing Type** and **Send Date**, and choose the **Landing Page** the QR code leads to — then fill in that page’s headline, photos or offering memorandum.' },
      { title: 'Create it', body: 'Click **Create Mailing**. Its detail window opens.' },
      { title: 'Add recipients', body: 'On **Recipients**, click **Add Recipients** and choose **From CRM Contacts**, **Upload CSV**, **Add Manually** or **Neighbor Lookup**.' },
      { title: 'Get the QR code for printing', body: 'On **Overview**, download the QR code as **PNG** or **SVG** and put it on your design in Canva or Vistaprint. **Copy URL** copies the link.', tip: 'The SVG stays sharp at any size. Every piece in the mailing uses the same code.' },
      { title: 'Mark it sent', body: 'Set the **Status** to **Sent (in the mail)** when it goes out (on the **Edit** tab). It then shows under **Out in the mail**.' },
      { title: 'Watch results', body: 'The **Scans** and **Leads** tabs fill in as people scan and fill in the landing-page form. The response index shows scans per 100 pieces mailed.' },
    ],
    troubleshooting: [
      { problem: '“Name is required”', fix: 'Fill in **Mailing Name**.' },
      { problem: 'Does the CRM print or post the mail?', fix: 'No — it gives you the QR code and the recipient list (**Export CSV**). You print and send through your usual print shop.' },
      { problem: 'Who scanned it?', fix: 'Everyone gets the same code, so scans can’t be tied to a recipient. Leads who fill in the landing-page form appear on **Leads** and become contacts.' },
      { problem: '“Deal Machine API not configured”', fix: 'Neighbor Lookup needs your office to set it up. Use another way to add recipients for now.' },
    ],
    related: ['radius-mailing', 'website-leads'],
  },
  {
    id: 'website-leads',
    category: 'marketing',
    title: 'Work your website leads',
    summary: 'Leads from the website are assigned to an agent automatically, added as contacts, and can start a drip.',
    minutes: 2,
    keywords: ['website leads', 'inquiry', 'inquiries', 'round robin', 'lead rotation', 'web lead', 'captured leads'],
    routes: ['leads'],
    action: { label: 'Open Website Leads', route: 'leads' },
    steps: [
      { title: 'Get notified', body: 'When a website lead is yours, you get a bell notification and an email. Click the notification to open the lead — it’s already a contact in your book, and your auto-start drip begins if you set one up.' },
      { title: 'Find the lead', body: `${OPEN_TOOLS('Website Leads')} **Inquiries** lists every lead with who it went to and whether a drip started.` },
      { title: 'Work it from Contacts', body: 'Search for the person (top search box) and open them to call, email and log what happens.' },
      { title: 'Older form captures', body: 'On **Captured Leads**, click **Add to CRM** to turn a capture into a contact.' },
      { title: 'How leads are shared out', body: 'The **Round Robin** tab shows who is next in each lane (Residential, Commercial). A lead who is already a contact stays with their agent.' },
    ],
    troubleshooting: [
      { problem: 'I can’t reassign a lead', fix: 'Only an office admin can change the rotation or reassign a lead.' },
      { problem: 'The notification opens “That contact isn’t in your book”', fix: 'The lead belongs to another agent (you were told as the cross-specialty agent). Ask them, or your office admin, if you should work it.' },
    ],
    related: ['drip-sequence', 'log-activity'],
  },
  {
    id: 'cold-calls',
    category: 'marketing',
    title: 'Work a cold-call list with the Power Dialer',
    summary: 'Upload a list of owners, call through it one by one, log outcomes and turn good calls into contacts.',
    minutes: 6,
    keywords: ['cold call', 'dialer', 'power dialer', 'call list', 'prospecting', 'callback', 'dnc', 'do not call'],
    routes: ['coldcalls'],
    action: { label: 'Open Cold Calls', route: 'coldcalls' },
    steps: [
      { title: 'Upload a list', body: 'Open **Cold Calls** and click **Upload List**. Drop a CSV or TSV file.' },
      { title: 'Name and assign it', body: 'Check the **List Name** and **Assign To Agent**, then click **Next: Map Columns**.' },
      { title: 'Match columns', body: 'Match each column (owner name, property address, phones, emails…) and click **Import … Leads**. Leads whose phone matches an existing contact are flagged as possible duplicates.' },
      { title: 'Start dialing', body: 'Pick the list and click **Power Dialer**. It starts at the first new lead. Tap **Call** beside a number to dial it.', tip: 'Click **✦ Generate Call Script** for talking points about the property.' },
      { title: 'Log the outcome', body: 'Type **Call Notes**, then click **Called**, **Callback** (pick a date, then **Set Date** — it creates a call task), **DNC** (do not call) or **Convert**.' },
      { title: 'Convert a good lead', body: '**Convert** creates the contact (and the property) and copies your call notes into their timeline.' },
    ],
    troubleshooting: [
      { problem: 'Power Dialer is greyed out', fix: 'Every lead on the list has been called. Use the filters (**Callback**, **Called**) to go back to them.' },
      { problem: 'I set a callback but got no task', fix: 'Pick a **Callback Date** before clicking **Set Date**.' },
      { problem: 'I deleted a list by mistake', fix: 'Deleting a list (after you confirm) removes its leads and call notes for good — contacts you converted are kept. Upload the file again to start over.' },
    ],
    related: ['add-contact', 'tasks'],
  },
]
