// Properties & listings — written from pages/properties/*, the Listings
// board and RadiusMailingModal. **Bold** text is the exact on-screen label.

export default [
  {
    id: 'add-property',
    category: 'properties',
    title: 'Add a property or listing',
    summary: 'Add a listing with photos, price and the details for its type — multifamily, office, retail, land and more.',
    minutes: 4,
    keywords: ['new property', 'listing', 'add listing', 'building', 'multifamily', 'photos', 'address', 'mls'],
    routes: ['properties'],
    action: { label: 'Add a property now', route: 'properties', startNew: 'property' },
    steps: [
      { title: 'Open a blank property', body: 'On **Properties**, click **Add Property**.' },
      { title: 'Add photos', body: 'Drop photos on the **Photos** box (or click it). JPEG, PNG or WEBP, up to 10 MB each. They show on the public listing page.' },
      { title: 'Enter the address', body: '**Address** is the only required field. Add **Suite / Unit #**, **City**, **State**, **ZIP**, **County**, **Submarket** and **MLS #**. A map appears once the address is filled in.' },
      { title: 'Choose type and status', body: 'Pick the **Property Type** and **Status**. The price box and the detail fields change to suit the type — for example **Total Units** and **Unit Mix** for multifamily, **Class** and **Vacancy Rate %** for office.' },
      { title: 'Link the owner', body: 'Pick the owner under **Linked Contact**, and any co-owners under **Additional Contacts** — they’re carried onto a deal when you start one from this property.' },
      { title: 'Agents', body: '**Assigned Agent** defaults to you. Tick anyone sharing the commission under **Co-Agents**.' },
      { title: 'Save', body: 'Click **Save Property**. You’ll see “Property added”.', tip: 'Reopen the property to see its tabs (**Price History**, **Showings**, **Marketing**, **Comps**) and the **Start Deal**, **Announce** and **Share Link** buttons — they only appear once it’s saved.' },
    ],
    troubleshooting: [
      { problem: 'Nothing happens when I save', fix: 'Check the **Address** box — if it’s outlined red, it’s empty.' },
      { problem: '“Images only, max 10 MB each”', fix: 'Export the photo smaller, or as a JPEG, and try again.' },
      { problem: 'I changed the price and my deal changed too', fix: 'That’s on purpose: the list price and the deal value stay in step, and every change is recorded in **Price History**.' },
    ],
    related: ['property-tools', 'create-deal', 'listings-board'],
  },
  {
    id: 'property-tools',
    category: 'properties',
    title: 'Share, announce and track a listing',
    summary: 'Share link, Mass Email announcement, showings, comps, price history and the marketing checklist.',
    minutes: 3,
    keywords: ['share link', 'announce', 'showing', 'comps', 'price history', 'price reduction', 'marketing checklist', 'feedback'],
    routes: ['properties'],
    action: { label: 'Open Properties', route: 'properties' },
    steps: [
      { title: 'Open the property', body: 'Click it on **Properties**.' },
      { title: 'Share it', body: 'Click **Share Link** to copy a link to the public listing page — it works on social, email and text.' },
      { title: 'Announce it', body: 'Click **Announce** to email a Just Closed / New Listing announcement. It opens **Mass Email** with this property already picked — see **Send a mass email or deal announcement**.' },
      { title: 'Log showings', body: 'On the **Showings** tab, click **Log Showing**. Enter the **Date & Time**, the buyer’s agent, their **Feedback** and a **Rating**.' },
      { title: 'Add comps', body: 'On the **Comps** tab, click **Add Comp** with at least the **Address** and **Sale Price**.' },
      { title: 'Check price history', body: 'The **Price History** tab records every price change automatically when you save a new list price.' },
      { title: 'Work the marketing checklist', body: 'The **Marketing** tab fills in a checklist when the listing is Active. Add your own steps with **Add a step…**.' },
    ],
    related: ['mass-email', 'radius-mailing', 'add-property'],
  },
  {
    id: 'radius-mailing',
    category: 'properties',
    title: 'Get a list of owners near a property',
    summary: 'Radius Mailing finds the owners of nearby properties and downloads them as a CSV for your print shop.',
    minutes: 2,
    keywords: ['radius', 'neighbors', 'nearby', 'just sold', 'farm', 'mailing list', 'csv', 'owners'],
    routes: ['properties'],
    action: { label: 'Open Properties', route: 'properties' },
    steps: [
      { title: 'Find the envelope icon', body: 'On **Properties**, click the envelope icon on the property’s card (or row). Its tooltip says “Radius Mailing”.' },
      { title: 'Pick the campaign and radius', body: 'Choose a **Campaign Type** (Just Sold, Just Listed, Open House…) and a **Search Radius** from 0.25 to 5 miles.' },
      { title: 'Search', body: 'Click **Find Contacts Within Radius**. The first search can take a little while as addresses are located on the map.' },
      { title: 'Download', body: 'Tick who to include (**All** / **None**), then click **Download … as CSV**.' },
    ],
    troubleshooting: [
      { problem: '“Could not geocode this property”', fix: 'Fill in the property’s address, city and state, save it, and try again.' },
      { problem: 'Nobody was found', fix: 'It finds the **Linked Contact** of other properties in the CRM. Link owners to nearby properties so they turn up — or use **Neighbor Lookup** in Mail Campaigns.' },
      { problem: 'Did it mail anything?', fix: 'No — it only makes a CSV. To track a mailing with QR codes, use **Mail Campaigns**.' },
    ],
    related: ['mail-campaign', 'add-property'],
  },
  {
    id: 'listings-board',
    category: 'properties',
    title: 'Manage listings on the Listings board',
    summary: 'See every listing by status and drag it to a new one.',
    minutes: 1,
    keywords: ['listings', 'listing status', 'active', 'pending', 'sold', 'off market', 'cancelled', 'expired'],
    routes: ['pipeline'],
    action: { label: 'Open Pipeline', route: 'pipeline' },
    steps: [
      { title: 'Open the Listings board', body: 'Go to **Pipeline** and click **Listings** at the top.' },
      { title: 'Move a listing', body: 'Drag a card to **Active**, **Pending**, **Off Market**, **Sold**, **Leased** or **Cancelled**.' },
      { title: 'Read the flags', body: 'Cards warn when the **listing expires** soon, show offers and **Under contract**, and how long it’s been on the market.' },
      { title: 'Open or start the deal', body: 'Click a card to open its deal — or, if it has none yet, a new deal pre-filled with the address and property.' },
    ],
    troubleshooting: [
      { problem: 'Removing a listing', fix: 'The trash icon (“Remove listing”) permanently deletes the property. Linked deals are kept but unlinked. To take it off the market without deleting, drag it to **Off Market** or **Cancelled**.' },
    ],
    related: ['add-property', 'create-deal'],
  },
]
